---
title: "EAVE II Data Dictionary"
author: "EAVE II Analysts"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  pdf_document:
    toc: true
    toc_depth: 1
    number_sections: true
geometry: "left=1.5cm,right=1.5cm,top=2cm,bottom=2cm"

---
\fontsize{10}{22}


```{r setup, message=FALSE, warning=FALSE, echo=F, include=T}
library(here)
# Read in functions from code/00_functions
source(here("./code/00_functions.R"))


```

```{r logo, echo=F}
htmltools::img(src = image_uri(file.path(here("./logo/EAVEII logo.png"))),
               style="position:absolute; top:0; right:0; padding:10px; width:200px;")

```

```{r data_load, results='asis', message=FALSE, warning=FALSE, echo=F, include=T}
# Load in all data sheets from data dictionary excel file
data_dictionary <- read_excel_allsheets(filename= (here("./data_dictionary/EAVEII_data_dictionary.xlsx"))) # From 00_functions

# Extract 1st tab as the main
main_tab <- data_dictionary[[1]]



```




```{r metadata_loop, results='asis',message=FALSE, warning=FALSE, echo=F, width=50}
# Create a loop that takes each sheet individually, extracts the sheet name (for header) and
# reformats excel spreadsheet so it can reformat it into R Markdown document

for(i in 2:length(data_dictionary)){ # Sheet 1 = "Main" so start from sheet 2 to the rest of the sheets

  ## Extract baseline information from sheet
  h1 <- names(data_dictionary[i]) # The sheet name will be header 1 (h1)
  data_input <- data_dictionary[[i]] # Extract data from list as a dataframe (requires [[]])
  
  # Assigns header 1 (h1) as the sheet name to rmd
  cat("\n# ", h1, "\n")
  
  ## Dataset information
  # Header
  cat("\n## ", "Data information", "\n")
  
  metadata_row <- match(h1, main_tab$`Dataset name`) # Match the row from the main tab (1st sheet)
  main_tab_input <- main_tab[metadata_row,] # Subset to the row in the main tab corresponding to the ith sheet
  
  metadata_tbl <- dataset_metadata_fn(main_tab_input) # # From 00_functions
  
  
  
  ## Variable table
  # Header
  cat("\n## ", "Variable information", "\n")
  
  variables_tbl <- variable_metadata_fn(data_input) # From 00_functions


  


  
}

```


